
platform :ios, '9.0'

use_frameworks!

# pod install --verbose --no-repo-update

# 适配各个iOS版本 pod库最好指定最低版本

target 'ExperimentProduct' do

# 网络
pod 'Moya/RxSwift'

pod 'RxCocoa'

pod 'RxDataSources', '~> 3.0'  # RxSwift中用于设置UITableView/UICollectionView data sources

# 解析 JSON数据
pod 'SwiftyJSON'
pod 'HandyJSON'

# 自动布局框架
pod 'SnapKit'

# 分页控制器
pod 'TYPagerController'

# 集Animation和UI与一身
#pod 'MaterialKit'

# 图片加载、缓存
#pod 'Kingfisher'
pod 'libwebp'
#pod 'iOS-WebP'

# 消息及应用通知组件
#pod 'Whisper'

# 很多漂亮的加载指示器
#pod 'NVActivityIndicatorView'

# 图片选择器
#pod 'ImagePicker'
pod 'TZImagePickerController'
# 图片裁剪
pod 'JPImageresizerView'

# 图片视频浏览
pod 'JXPhotoBrowser'

# 操作指南、新手教程
#pod 'Instructions'

# 转场动画
#pod 'StarWars'

# 数字变形过渡动画，用于金额数字变动或者时间
#pod 'NumberMorphView'

# 自定义的进度加载动画
#pod 'FillableLoaders'

# 支持Hashtags、Mentions、Links响应事件
pod 'ActiveLabel'

# TextField
#pod 'TextFieldEffects'
#pod 'SkyFloatingLabelTextField'

# TextView
#pod 'NextGrowingTextView'

# 日志
pod 'XCGLogger'

# 代码风格检查
pod 'SwiftLint'

# 键盘管理
pod 'WHC_KeyboardManager'

# 空白页 对于tableHeaderView或则tableFooterView处理不到位
# pod 'EmptyKit'

# 骨架动画
pod 'TABAnimated'

# 上下拉刷新
pod "ESPullToRefresh"

# cache
pod 'YYCache'

# 视频缓存
pod 'KTVHTTPCache', '~> 2.0'

# 启动广告 是个oc库 还有依赖库
#pod 'XHLaunchAd'

# 检查内存泄露
pod 'MLeaksFinder', :git => 'https://github.com/Zepo/MLeaksFinder.git', :configurations => ['Debug']
pod 'FBRetainCycleDetector', :git => 'https://github.com/facebook/FBRetainCycleDetector.git' ,:branch => 'main', :configurations => ['Debug']

# 还在研究
#pod 'IGListKit', '~> 4.0.0'
## 牵扯到 Texture DeepDiff
#pod 'Texture'
#pod 'EasyKits'
pod 'Texture/IGListKit'

# 对于比例自适应
#pod 'AutoInch'

# 控件的属性添加
pod 'Then'

# 控件的layout
#pod 'SteviaLayout'

# 类似微博、抖音、网易云等个人详情页滑动嵌套效果 https://github.com/QuintGao/GKPageScrollView
#pod 'GKPageScrollView/Swift'
#pod 'GKPageSmoothView/Swift'

end

